# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto_sample_pb2 as proto__sample__pb2


class VirtualLearningMonitorStub(object):
    """online class monitoring system
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.process = channel.unary_unary(
                '/VirtualLearningMonitor/process',
                request_serializer=proto__sample__pb2.UserData.SerializeToString,
                response_deserializer=proto__sample__pb2.ReturnData.FromString,
                )


class VirtualLearningMonitorServicer(object):
    """online class monitoring system
    """

    def process(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VirtualLearningMonitorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'process': grpc.unary_unary_rpc_method_handler(
                    servicer.process,
                    request_deserializer=proto__sample__pb2.UserData.FromString,
                    response_serializer=proto__sample__pb2.ReturnData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VirtualLearningMonitor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VirtualLearningMonitor(object):
    """online class monitoring system
    """

    @staticmethod
    def process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/VirtualLearningMonitor/process',
            proto__sample__pb2.UserData.SerializeToString,
            proto__sample__pb2.ReturnData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
